export const fonts = [
  { id: 'special-elite', label: 'Special Elite', family: '"Special Elite", "Courier New", monospace' },
  { id: 'rubbed-on', label: 'Rubbed-on', family: '"Rubbed-on", "Rubik Dirt", "Special Elite", "Courier New", monospace' },
  { id: 'vibrant', label: 'Vibrant', family: '"Vibrant", "Cormorant Garamond", "Libre Bodoni", Georgia, serif' },
  { id: 'cooper', label: 'Cooper Black', family: '"Cooper Black", "Cooper Std Black", "Ultra", Georgia, serif' },
  { id: 'bebas', label: 'Bebas Neue', family: '"Bebas Neue", Anton, Impact, sans-serif' },
  { id: 'bodoni', label: 'Bodoni', family: '"Libre Bodoni", "Bodoni 72", Didot, Georgia, serif' },
  { id: 'playfair', label: 'Playfair', family: '"Playfair Display", "Times New Roman", serif' },
  { id: 'cormorant', label: 'Cormorant', family: '"Cormorant Garamond", Georgia, serif' },
  { id: 'baskerville', label: 'Baskerville', family: '"Libre Baskerville", Georgia, serif' },
  { id: 'abril', label: 'Abril Fatface', family: '"Abril Fatface", Georgia, serif' },
  { id: 'cinzel', label: 'Cinzel', family: '"Cinzel", Georgia, serif' },
  { id: 'imfell', label: 'IM Fell English', family: '"IM Fell English SC", Georgia, serif' },
  { id: 'limelight', label: 'Limelight', family: '"Limelight", Georgia, serif' },
  { id: 'rye', label: 'Rye', family: '"Rye", Georgia, serif' },
  { id: 'ewert', label: 'Ewert', family: '"Ewert", Georgia, serif' },
  { id: 'almendra', label: 'Almendra Display', family: '"Almendra Display", Georgia, serif' },
  { id: 'medieval', label: 'MedievalSharp', family: '"MedievalSharp", Georgia, serif' },
  { id: 'metamorphous', label: 'Metamorphous', family: '"Metamorphous", Georgia, serif' },
  { id: 'grenze', label: 'Grenze Gotisch', family: '"Grenze Gotisch", Georgia, serif' },
  { id: 'unifraktur', label: 'UnifrakturCook', family: '"UnifrakturCook", Georgia, serif' },
  { id: 'fredericka', label: 'Fredericka', family: '"Fredericka the Great", Georgia, serif' },
  { id: 'bungee-inline', label: 'Bungee Inline', family: '"Bungee Inline", Impact, sans-serif' },
  { id: 'bungee-shade', label: 'Bungee Shade', family: '"Bungee Shade", Impact, sans-serif' },
  { id: 'monoton', label: 'Monoton', family: '"Monoton", Impact, sans-serif' },
  { id: 'astloch', label: 'Astloch', family: '"Astloch", Georgia, serif' },
  { id: 'mystery', label: 'Mystery Quest', family: '"Mystery Quest", Georgia, serif' },
  { id: 'great-vibes', label: 'Great Vibes', family: '"Great Vibes", cursive' },
  { id: 'parisienne', label: 'Parisienne', family: '"Parisienne", cursive' },
  { id: 'yesteryear', label: 'Yesteryear', family: '"Yesteryear", cursive' },
  { id: 'sacramento', label: 'Sacramento', family: '"Sacramento", cursive' },
  { id: 'pacifico', label: 'Pacifico', family: '"Pacifico", cursive' },
  { id: 'lobster', label: 'Lobster', family: '"Lobster", cursive' },
  { id: 'berkshire', label: 'Berkshire Swash', family: '"Berkshire Swash", cursive' },
  { id: 'songti', label: 'Songti', family: '"Songti SC", "STSong", serif' },
  { id: 'kaiti', label: 'Kaiti', family: '"Kaiti SC", "KaiTi", serif' },
];
